name: glitchmaps
services:
  app:
    build: .
    ports:
      - "8216:8216"
  strapidb:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=strapi
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  strapi:
    container_name: strapi
    build:
      context: ./api/.
      dockerfile: Dockerfile.prod
    image: strapi:latest
    restart: unless-stopped
    env_file: ./api/.env
    environment:
      NODE_ENV: production
    volumes:
      - ./api/config:/opt/app/config
      - ./api/src:/opt/app/src
      - ./api/package.json:/opt/app/package.json
      - ./api/yarn.lock:/opt/app/yarn.lock
      - ./api/.env:/opt/app/.env
      - ./api/public/:/opt/app/public/
    ports:
      - "1337:1337"
    depends_on:
      - strapidb
networks:
  default:
    external: true
    name: npm
